// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: shopcategory.proto

package go_micro_service_shop_category

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ShopCategory service

func NewShopCategoryEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ShopCategory service

type ShopCategoryService interface {
	CreateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*CreateCategoryResponse, error)
	UpdateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*UpdateCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...client.CallOption) (*DeleteCategoryResponse, error)
	FindCategoryByName(ctx context.Context, in *FindByNameRequest, opts ...client.CallOption) (*CategoryResponse, error)
	FindCategoryByID(ctx context.Context, in *FindByIdRequest, opts ...client.CallOption) (*CategoryResponse, error)
	FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, opts ...client.CallOption) (*FindAllResponse, error)
	FindCategoryByParent(ctx context.Context, in *FindByParentRequest, opts ...client.CallOption) (*FindAllResponse, error)
	FindAllCategory(ctx context.Context, in *FindAllRequest, opts ...client.CallOption) (*FindAllResponse, error)
}

type shopCategoryService struct {
	c    client.Client
	name string
}

func NewShopCategoryService(name string, c client.Client) ShopCategoryService {
	return &shopCategoryService{
		c:    c,
		name: name,
	}
}

func (c *shopCategoryService) CreateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*CreateCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.CreateCategory", in)
	out := new(CreateCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) UpdateCategory(ctx context.Context, in *CategoryRequest, opts ...client.CallOption) (*UpdateCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.UpdateCategory", in)
	out := new(UpdateCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...client.CallOption) (*DeleteCategoryResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.DeleteCategory", in)
	out := new(DeleteCategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) FindCategoryByName(ctx context.Context, in *FindByNameRequest, opts ...client.CallOption) (*CategoryResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.FindCategoryByName", in)
	out := new(CategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) FindCategoryByID(ctx context.Context, in *FindByIdRequest, opts ...client.CallOption) (*CategoryResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.FindCategoryByID", in)
	out := new(CategoryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, opts ...client.CallOption) (*FindAllResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.FindCategoryByLevel", in)
	out := new(FindAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) FindCategoryByParent(ctx context.Context, in *FindByParentRequest, opts ...client.CallOption) (*FindAllResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.FindCategoryByParent", in)
	out := new(FindAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopCategoryService) FindAllCategory(ctx context.Context, in *FindAllRequest, opts ...client.CallOption) (*FindAllResponse, error) {
	req := c.c.NewRequest(c.name, "ShopCategory.FindAllCategory", in)
	out := new(FindAllResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShopCategory service

type ShopCategoryHandler interface {
	CreateCategory(context.Context, *CategoryRequest, *CreateCategoryResponse) error
	UpdateCategory(context.Context, *CategoryRequest, *UpdateCategoryResponse) error
	DeleteCategory(context.Context, *DeleteCategoryRequest, *DeleteCategoryResponse) error
	FindCategoryByName(context.Context, *FindByNameRequest, *CategoryResponse) error
	FindCategoryByID(context.Context, *FindByIdRequest, *CategoryResponse) error
	FindCategoryByLevel(context.Context, *FindByLevelRequest, *FindAllResponse) error
	FindCategoryByParent(context.Context, *FindByParentRequest, *FindAllResponse) error
	FindAllCategory(context.Context, *FindAllRequest, *FindAllResponse) error
}

func RegisterShopCategoryHandler(s server.Server, hdlr ShopCategoryHandler, opts ...server.HandlerOption) error {
	type shopCategory interface {
		CreateCategory(ctx context.Context, in *CategoryRequest, out *CreateCategoryResponse) error
		UpdateCategory(ctx context.Context, in *CategoryRequest, out *UpdateCategoryResponse) error
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, out *DeleteCategoryResponse) error
		FindCategoryByName(ctx context.Context, in *FindByNameRequest, out *CategoryResponse) error
		FindCategoryByID(ctx context.Context, in *FindByIdRequest, out *CategoryResponse) error
		FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, out *FindAllResponse) error
		FindCategoryByParent(ctx context.Context, in *FindByParentRequest, out *FindAllResponse) error
		FindAllCategory(ctx context.Context, in *FindAllRequest, out *FindAllResponse) error
	}
	type ShopCategory struct {
		shopCategory
	}
	h := &shopCategoryHandler{hdlr}
	return s.Handle(s.NewHandler(&ShopCategory{h}, opts...))
}

type shopCategoryHandler struct {
	ShopCategoryHandler
}

func (h *shopCategoryHandler) CreateCategory(ctx context.Context, in *CategoryRequest, out *CreateCategoryResponse) error {
	return h.ShopCategoryHandler.CreateCategory(ctx, in, out)
}

func (h *shopCategoryHandler) UpdateCategory(ctx context.Context, in *CategoryRequest, out *UpdateCategoryResponse) error {
	return h.ShopCategoryHandler.UpdateCategory(ctx, in, out)
}

func (h *shopCategoryHandler) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, out *DeleteCategoryResponse) error {
	return h.ShopCategoryHandler.DeleteCategory(ctx, in, out)
}

func (h *shopCategoryHandler) FindCategoryByName(ctx context.Context, in *FindByNameRequest, out *CategoryResponse) error {
	return h.ShopCategoryHandler.FindCategoryByName(ctx, in, out)
}

func (h *shopCategoryHandler) FindCategoryByID(ctx context.Context, in *FindByIdRequest, out *CategoryResponse) error {
	return h.ShopCategoryHandler.FindCategoryByID(ctx, in, out)
}

func (h *shopCategoryHandler) FindCategoryByLevel(ctx context.Context, in *FindByLevelRequest, out *FindAllResponse) error {
	return h.ShopCategoryHandler.FindCategoryByLevel(ctx, in, out)
}

func (h *shopCategoryHandler) FindCategoryByParent(ctx context.Context, in *FindByParentRequest, out *FindAllResponse) error {
	return h.ShopCategoryHandler.FindCategoryByParent(ctx, in, out)
}

func (h *shopCategoryHandler) FindAllCategory(ctx context.Context, in *FindAllRequest, out *FindAllResponse) error {
	return h.ShopCategoryHandler.FindAllCategory(ctx, in, out)
}
